### ISSUE TITLE
Document zero-perspective transform quirk

### ISSUE THREAD

**Issue by miketaylr** [whatwg/compat#48]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1009150.

It seems IE 11 and Edge also implemented this quirk (or had it).

@karlcow made a test (you should see a yellow box if the UA supports this quirk): http://codepen.io/anon/pen/ZGKmLQ?editors=110

**Comment by karlcow** [comment]
So I created another pen to partly better show the issue:

```css
p.zero {
  background-color: pink;
  width: 200px;
  transform: perspective(0px) translate(260px, 0);
}

p.notzero {  background-color: pink;
  width: 200px;
  transform: perspective(0.0001px) translate(260px, 0);
}

div {
  width: 200px;
  background-color: yellow;
}
```
And this is the result:

* Left: Firefox Nightly 48.0a1 (2016-04-03)
* Center: Safari Technology Preview Version 9.1.1 (11601.6.10, 11602.1.25)
* Right: Opera Beta 37.0.2178.4

![capture d ecran 2016-04-04 a 09 27 37](https://cloud.githubusercontent.com/assets/505230/14235969/ef8db0da-fa47-11e5-8aef-dd4c6af62af5.png)
